package dev.iconfy

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.File

/** One resolved icon placement: optional category, set prefix, Iconify name, and converted vector. */
internal data class IconEntry(
    val category: String,
    val prefix: String,
    /** Optional override for the prefix segment's object name (blank = derive from [prefix]). */
    val prefixDisplay: String,
    val name: String,
    /** Optional accessor-name override; when blank the accessor is derived from [name]. */
    val display: String,
    val image: VectorImage,
)

/**
 * Emits a single `object <accessor> { object <Prefix> { val <Icon>: ImageVector } }` file with
 * lazily built, memoized [ImageVector]s. Generated code depends only on `androidx.compose.ui`.
 * Nesting by prefix means same-named icons in different sets never collide.
 */
internal object IconfyCodegen {

    private val IMAGE_VECTOR = ClassName("androidx.compose.ui.graphics.vector", "ImageVector")
    private val BUILDER = IMAGE_VECTOR.nestedClass("Builder")
    private val ADD_PATH_NODES = MemberName("androidx.compose.ui.graphics.vector", "addPathNodes")
    private val SOLID_COLOR = ClassName("androidx.compose.ui.graphics", "SolidColor")
    private val COLOR = ClassName("androidx.compose.ui.graphics", "Color")
    private val PATH_FILL_TYPE = ClassName("androidx.compose.ui.graphics", "PathFillType")
    private val STROKE_CAP = ClassName("androidx.compose.ui.graphics", "StrokeCap")
    private val STROKE_JOIN = ClassName("androidx.compose.ui.graphics", "StrokeJoin")
    private val DP = MemberName("androidx.compose.ui.unit", "dp")

    /** Nominal default display size (dp), matching Material icons; source viewBox varies per set. */
    private const val BASE_SIZE = 24f

    fun generate(packageName: String, accessorName: String, icons: List<IconEntry>, outDir: File) {
        val root = TypeSpec.objectBuilder(accessorName)
        val byCategory = icons.groupBy { it.category }

        // Uncategorized icons: prefix objects directly under the root (Iconfy.Mdi.Home).
        byCategory[""]?.let { addPrefixObjects(root, accessorName, it) }

        // Categorized icons: a nested object per category (Iconfy.Dashboard.Mdi.Home).
        byCategory.filterKeys { it.isNotEmpty() }.toSortedMap().forEach { (category, entries) ->
            val categoryName = Names.pascal(category)
            val categoryObj = TypeSpec.objectBuilder(categoryName)
            addPrefixObjects(categoryObj, "$accessorName.$categoryName", entries)
            root.addType(categoryObj.build())
        }

        FileSpec.builder(packageName, accessorName)
            .addFileComment("Generated by iconfy. Do not edit.")
            .addType(root.build())
            .build()
            .writeTo(outDir)
    }

    /** Adds one nested object per prefix segment (each holding the icon accessors) under [parent]. */
    private fun addPrefixObjects(parent: TypeSpec.Builder, fqParent: String, entries: List<IconEntry>) {
        val byPrefixName = entries.groupBy { Names.pascal(it.prefixDisplay.ifEmpty { it.prefix }) }.toSortedMap()
        for ((prefixName, group) in byPrefixName) {
            val prefixObj = TypeSpec.objectBuilder(prefixName)
            val used = mutableSetOf<String>()
            for (entry in group.sortedBy { it.display.ifEmpty { it.name } }) {
                val propName = uniquify(Names.pascal(entry.display.ifEmpty { entry.name }), used)
                addIcon(prefixObj, "$fqParent.$prefixName.$propName", propName, entry.image)
            }
            parent.addType(prefixObj.build())
        }
    }

    private fun uniquify(base: String, used: MutableSet<String>): String {
        if (used.add(base)) return base
        var i = 2
        while (!used.add("$base$i")) i++
        return "$base$i"
    }

    private fun addIcon(group: TypeSpec.Builder, fqName: String, propName: String, image: VectorImage) {
        val backing = "_" + propName.replaceFirstChar { it.lowercaseChar() }

        // Normalize the default display size to BASE_SIZE dp (keeping viewport = the icon's real
        // coordinate space) so a 256-viewBox set (Phosphor) renders at the same size as a 24 one
        // (Material), while non-square icons keep their aspect ratio.
        val maxViewport = maxOf(image.viewportWidth, image.viewportHeight).takeIf { it > 0f } ?: BASE_SIZE
        val defaultWidth = BASE_SIZE * image.viewportWidth / maxViewport
        val defaultHeight = BASE_SIZE * image.viewportHeight / maxViewport

        val body = CodeBlock.builder()
            .addStatement("%N?.let { return it }", backing)
            .add("val vector = %T(\n", BUILDER)
            .indent()
            .add("name = %S,\n", fqName)
            .add("defaultWidth = %Lf.%M,\n", num(defaultWidth), DP)
            .add("defaultHeight = %Lf.%M,\n", num(defaultHeight), DP)
            .add("viewportWidth = %Lf,\n", num(image.viewportWidth))
            .add("viewportHeight = %Lf,\n", num(image.viewportHeight))
            .unindent()
            .add(").apply {\n")
            .indent()
        image.nodes.forEach { emitNode(body, it) }
        body.unindent()
            .add("}.build()\n")
            .addStatement("%N = vector", backing)
            .addStatement("return vector")

        group.addProperty(
            PropertySpec.builder(backing, IMAGE_VECTOR.copy(nullable = true), KModifier.PRIVATE)
                .mutable(true).initializer("null").build()
        )
        group.addProperty(
            PropertySpec.builder(propName, IMAGE_VECTOR)
                .getter(FunSpec.getterBuilder().addCode(body.build()).build())
                .build()
        )
    }

    private fun emitNode(body: CodeBlock.Builder, node: VNode) {
        when (node) {
            is VPath -> emitPath(body, node)
            is VGroup -> emitGroup(body, node)
        }
    }

    private fun emitPath(body: CodeBlock.Builder, p: VPath) {
        body.add("addPath(\n").indent()
        body.add("pathData = %M(%S),\n", ADD_PATH_NODES, p.pathData)

        val hasFill = p.fillColor != null && (p.fillColor ushr 24) != 0L
        if (hasFill) {
            body.add("fill = %T(%T(0x%LL)),\n", SOLID_COLOR, COLOR, hex(p.fillColor!!))
            if (p.fillAlpha != 1f) body.add("fillAlpha = %Lf,\n", num(p.fillAlpha))
        }
        body.add("pathFillType = %T.%L,\n", PATH_FILL_TYPE, if (p.fillType == "evenOdd") "EvenOdd" else "NonZero")

        val hasStroke = p.strokeColor != null && (p.strokeColor ushr 24) != 0L && p.strokeWidth > 0f
        if (hasStroke) {
            body.add("stroke = %T(%T(0x%LL)),\n", SOLID_COLOR, COLOR, hex(p.strokeColor!!))
            if (p.strokeAlpha != 1f) body.add("strokeAlpha = %Lf,\n", num(p.strokeAlpha))
            body.add("strokeLineWidth = %Lf,\n", num(p.strokeWidth))
            body.add("strokeLineCap = %T.%L,\n", STROKE_CAP, capName(p.strokeCap))
            body.add("strokeLineJoin = %T.%L,\n", STROKE_JOIN, joinName(p.strokeJoin))
            if (p.strokeMiter != 4f) body.add("strokeLineMiter = %Lf,\n", num(p.strokeMiter))
        }
        body.unindent().add(")\n")
    }

    private fun emitGroup(body: CodeBlock.Builder, g: VGroup) {
        body.add("group(\n").indent()
        if (g.rotation != 0f) body.add("rotate = %Lf,\n", num(g.rotation))
        if (g.pivotX != 0f) body.add("pivotX = %Lf,\n", num(g.pivotX))
        if (g.pivotY != 0f) body.add("pivotY = %Lf,\n", num(g.pivotY))
        if (g.scaleX != 1f) body.add("scaleX = %Lf,\n", num(g.scaleX))
        if (g.scaleY != 1f) body.add("scaleY = %Lf,\n", num(g.scaleY))
        if (g.translateX != 0f) body.add("translationX = %Lf,\n", num(g.translateX))
        if (g.translateY != 0f) body.add("translationY = %Lf,\n", num(g.translateY))
        g.clipPathData?.let { body.add("clipPathData = %M(%S),\n", ADD_PATH_NODES, it) }
        body.unindent().add(") {\n").indent()
        g.children.forEach { emitNode(body, it) }
        body.unindent().add("}\n")
    }

    /** Compact float literal without KotlinPoet inferring a type, e.g. 24.0 -> "24.0". */
    private fun num(value: Float): String {
        val l = value.toLong()
        return if (l.toFloat() == value) "$l.0" else value.toString()
    }

    private fun hex(argb: Long): String = String.format("%08X", argb)

    private fun capName(cap: String) = when (cap.lowercase()) {
        "round" -> "Round"
        "square" -> "Square"
        else -> "Butt"
    }

    private fun joinName(join: String) = when (join.lowercase()) {
        "round" -> "Round"
        "bevel" -> "Bevel"
        else -> "Miter"
    }
}

/** Icon-name → Kotlin identifier (`arrow-left` -> `ArrowLeft`, `1password` -> `_1password`). */
internal object Names {
    fun pascal(raw: String): String {
        val parts = raw.split(Regex("[^A-Za-z0-9]+")).filter { it.isNotEmpty() }
        val sb = StringBuilder()
        for (p in parts) {
            sb.append(p[0].uppercaseChar())
            if (p.length > 1) sb.append(p.substring(1))
        }
        var name = sb.toString().ifEmpty { "Icon" }
        if (name[0].isDigit()) name = "_$name"
        return name
    }
}
